[package]
name = "tm"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
axum = { version = "0.7.9" }
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread", "signal"] }

[dev-dependencies]
reqwest = "0.12.9"
serde_json = "1.0.134"
